name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instalar dependências
        run: yarn
      - name: Install Packages
        run: cd ./finance-front && yarn install
      - name: Deploy to GH Pages
        run: yarn deploy
      - name: Updating Domain
        run: |
          git config --global user.email ${{secrets.GIT_EMAIL}}
          git config --global user.name ${{secrets.GIT_USERNAME}}
          git remote set-url origin https://${{secrets.GIT_TOKEN}}>@github.com/${{secrets.GIT_USERNAME}}/Finance.git
          npm run deploy
